/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.meiresearch.android.plotprojects;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.plotprojects.exampleapp.MainActivity;


@Kroll.module(name="ComMeiresearchAndroidPlotprojects", id="com.meiresearch.android.plotprojects")
public class ComMeiresearchAndroidPlotprojectsModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ComMeiresearchAndroidPlotprojectsModule";
	private static final boolean DBG = TiConfig.LOGD;

	private static final String isEnabled = 'false';
	private static final String version = '0.00.00';

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public ComMeiresearchAndroidPlotprojectsModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate A");
		// put module init code that needs to run when the application is created
//		Plot.init(this);
//
//		Log.d(LCAT, "inside onAppCreate B");
//
//		isEnabled = Plot.isEnabled();
//		version = Plot.getVersion();
//
//		Log.d(LCAT, "inside onAppCreate C");
//
//		Log.d(LCAT, "Is Plot Enabled? - ", isEnabled);
//		Log.d(LCAT, "Plot Version is - ", version);

	}

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(LCAT, "example called");
		return "hello world";
	}

	// Properties
	@Kroll.method
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}


	@Kroll.method
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}

}

